import type { Metadata } from 'next';
import './globals.css';
import Footer from './components/footer/Footer';

export const metadata: Metadata = {
    title: 'Disney App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className='bg-stone-900 w-full min-h-screen max-h-full'>
                {children}
                <Footer />
            </body>
        </html>
    )
}
