export const starwars_characters = [
    {tmdb_id: 4, name: "Carrie Fisher", profil_path: "/utKPqWm9MAcL6NqN0Kd71dWUmXM.jpg", character: "Leia Organa"},
    {tmdb_id: 2, name: "Mark Hamill", profil_path: "/2ZulC2Ccq1yv3pemusks6Zlfy2s.jpg", character: "Luke Skywalker"},
    {tmdb_id: 3, name: "Harrison Ford", profil_path: "/zVnHagUvXkR2StdOtquEwsiwSVt.jpg", character: "Han Solo"},
    {tmdb_id: 3896, name: "Liam Neeson", profil_path: "/bboldwqSC6tdw2iL6631c98l2Mn.jpg", character: "Qui-Gon Jinn"},
    {tmdb_id: 3061, name: "Ewan McGregor", profil_path: "/qYRGu6NIqkUYIO7ftso110WNQ6P.jpg", character: "Obi-Wan Kenobi"},
    {tmdb_id: 17244, name: "Hayden Christensen", profil_path: "/RuwAecNK9VDeTrfw6LUE4q4rIt.jpg", character: "Anakin Skywalker / Darth Vader"},
    {tmdb_id: 524, name: "Natalie Portman", profil_path: "/yBlYPhlrLyq38ftGHHtqGpCZwq3.jpg", character: "Padmé Amidala"},
    {tmdb_id: 1315036, name: "Daisy Ridley", profil_path: "/n8kBnNOi9VmELHJy3FdZjrSN9zT.jpg", character: "Rey"},
    {tmdb_id: 1023139, name: "Adam Driver", profil_path: "/fsbGQ1eZFgdsG1XnKlhNSvHsiGo.jpg", character: "Kylo Ren / Ben Solo"},
    {tmdb_id: 236695, name: "John Boyega", profil_path: "/3153CfpgZQXTzCY0i74WpJumMQe.jpg", character: "Finn"},
    {tmdb_id: 25072, name: "Oscar Isaac", profil_path: "/dW5U5yrIIPmMjRThR9KT2xH6nTz.jpg", character: "Poe Dameron"},
    {tmdb_id: 1663195, name: "Kelly Marie Tran", profil_path: "/7VisaPZicrZJyBa3AUQRDm9Yh0P.jpg", character: "Rose Tico"},
    {tmdb_id: 4784, name: "Laura Dern", profil_path: "/2Ryt0SsExqWrLTzBu6sZcbLwoDJ.jpg", character: "Vice Admiral Amilyn Holdo"},
    {tmdb_id: 93210, name: "Domhnall Gleeson", profil_path: "/uDbwncuKlqL0fAuucXSvgakJDrc.jpg", character: "General Hux"},
    {tmdb_id: 5, name: "Peter Cushing", profil_path: "/if5g03wn6uvHx7F6FxXHLebKc0q.jpg", character: "Grand Moff Tarkin"},
    {tmdb_id: 72855, name: "Felicity Jones", profil_path: "/35KdWSfTldNEdsn4MUGFIRoxJEu.jpg", character: "Jyn Erso"},
    {tmdb_id: 8688, name: "Diego Luna", profil_path: "/uH8sMbiMmy9sprKr1vJpoPBB40E.jpg", character: "Captain Cassian Andor"},
    {tmdb_id: 27762, name: "Ian McDiarmid", profil_path: "/jeoA2UQdKoz5rp4xLv0O32gzJ38.jpg", character: "Senator Palpatine"},
    {tmdb_id: 33190, name: "Pernilla August", profil_path: "/zICu2ItUmKh0dUcWtee49KpNDMq.jpg", character: "Shmi Skywalker"},
    {tmdb_id: 113, name: "Christopher Lee", profil_path: "/dA26fBr3t7mKqjn3OYW6kbD1LXM.jpg", character: "Count Dooku"},
    {tmdb_id: 2231, name: "Samuel L. Jackson", profil_path: "/nCJJ3NVksYNxIzEHcyC1XziwPVj.jpg", character: "Mace Windu"},
    {tmdb_id: 7242, name: "Temuera Morrison", profil_path: "/1ckHDFgKXJ8pazmvLCW7DeOKqA0.jpg", character: "Jango Fett / Boba Fett"},
    {tmdb_id: 33181, name: "Jimmy Smits", profil_path: "/dD04JlfW5N8bVrx7Cawn4A6g1xp.jpg", character: "Senator Bail Organa"},
    {tmdb_id: 1267329, name: "Lupita Nyong'o", profil_path: "/mJMpsADPpt0bmXEzs3ywrUiCkpD.jpg", character: "Maz Kanata"},
    {tmdb_id: 1333, name: "Andy Serkis", profil_path: "/eNGqhebQ4cDssjVeNFrKtUvweV5.jpg", character: "Supreme Leader Snoke"},
    {tmdb_id: 3799, name: "Billy Dee Williams", profil_path: "/dCiHLiCapPuRwKkM1ytVZ7PwYQY.jpg", character: "Lando Calrissian"},
    {tmdb_id: 5916, name: "Rosario Dawson", profil_path: "/1mm7JGHIUX3GRRGXEV9QCzsI0ao.jpg", character: "Ahsoka Tano"},
    {tmdb_id: 1583307, name: "Natasha Liu Bordizzo", profil_path: "/tROyGLEDMe8zpFQq09Fdbn42pGl.jpg", character: "Sabine Wren"},
    {tmdb_id: 17628, name: "Mary Elizabeth Winstead", profil_path: "/cBMtncBcUrKMTB8CifDG23THuCE.jpg", character: "Hera Syndulla"},
    {tmdb_id: 56614, name: "Ray Stevenson", profil_path: "/bI4r9prMaFiaky3uJTndq1lDlPR.jpg", character: "Baylan Skoll"},
    {tmdb_id: 1243496, name: "Ivanna Sakhno", profil_path: "/fHBNKEpExOMI6KTqk0JrPAZGsTT.jpg", character: "Shin Hati"},
    {tmdb_id: 113711, name: "Diana Lee Inosanto", profil_path: "/7EoE8xip9WlcaUmUm4mnowgdHbp.jpg", character: "Morgan Elsbeth"},
    {tmdb_id: 2243207, name: "Eman Esfandi", profil_path: "/qC7GMBvuMMGOrs2ahcROsdmkkz1.jpg", character: "Ezra Bridger"},
    {tmdb_id: 1253360, name: "Pedro Pascal", profil_path: "/nms0d0ExYtiOke82oqr3vOb3smF.jpg", character: "Din Djarin / The Mandalorian"},
    {tmdb_id: 51798, name: "Katee Sackhoff", profil_path: "/p8jMvubKMUE8thuRMZK5T6w1KbP.jpg", character: "Bo-Katan Kryze"},
    {tmdb_id: 1101, name: "Carl Weathers", profil_path: "/9Tot1ywxTQA3vFCcAjyK6h9Dao3.jpg", character: "Greef Karga"},
    {tmdb_id: 4808, name: "Giancarlo Esposito", profil_path: "/lBvDQZjxhIGMbH61iHnqerpbqHc.jpg", character: "Moff Gideon"},
    {tmdb_id: 1640, name: "Stellan Skarsgård", profil_path: "/x78BtYHElirO7Iw8bL4m8CnzRDc.jpg", character: "Luthen Rael"},
    {tmdb_id: 1390505, name: "Kyle Soller", profil_path: "/rLzduQpYJnZJKkXv3jRc7MDHwoI.jpg", character: "Syril Karn"},
    {tmdb_id: 1371297, name: "Adria Arjona", profil_path: "/2xAwAxrjZrgfyrNYToBIjg1ZeRB.jpg", character: "Bix Caleen"},
    {tmdb_id: 139654, name: "Genevieve O'Reilly", profil_path: "/xXPoflf99SEkK8yRpZPssH6y6S2.jpg", character: "Mon Mothma"},
    {tmdb_id: 1182597, name: "Denise Gough", profil_path: "/uGs5oHN1MK4tmU850fCw7d3Nx0h.jpg", character: "Dedra Meero"},
    {tmdb_id: 1204956, name: "Faye Marsay", profil_path: "/iYOrVuIxLRwyrwadrRdl0Y9WJhX.jpg", character: "Vel Sartha"},
    {tmdb_id: 27397, name: "Anton Lesser", profil_path: "/rKDn8ZHuIxl4Z3LLbUxvHdCOk0U.jpg", character: "Major Partagaz"},
    {tmdb_id: 928830, name: "Deborah Chow", profil_path: "/7XiXU4d7JqPGbhiGCvaRQclISRT.jpg", character: "Sash Ketter"},
    {tmdb_id: 2042908, name: "Moses Ingram", profil_path: "/u7I5f4Bgz7CI8G7fUOJDbFtd0qf.jpg", character: "Inquisitor Reva / Third Sister"},
    {tmdb_id: 1813472, name: "Vivien Lyra Blair", profil_path: "/uwXELU5rQKXOi7c2I7Q3R7Cf4Qb.jpg", character: "Leia Organa (enfant)"},
    {tmdb_id: 33192, name: "Joel Edgerton", profil_path: "/uFLxGHmPaNoTD6EMpMmu5bfP9Fr.jpg", character: "Owen Lars"},
    {tmdb_id: 131634, name: "Bonnie Piesse", profil_path: "/cF0HuGFh9Sk0ik1bAoaiVEedkou.jpg", character: "Beru Lars"},
    {tmdb_id: 21702, name: "Ming-Na Wen", profil_path: "/eqCzFF83It56cUdjpskzvg8jgq.jpg", character: "Fennec Shand"},
];